### ISSUE TITLE
Bug: Newly added photos of type specimens show as thumbnail, but not as larger depiction.

### ISSUE THREAD

**Issue by hhopkins77** [sfg-taxonpages/cockroach#2]
I have recently uploaded all holotype photographs from Queensland Museum to Cockroach Species File. When I went over to Cockroach TaxonPage, the thumbnail of the specimen labels works fine, but when I click on the thumbnails of the specimen photos this message appears in the box above : "Image was not found or format is not supported".

![image](https://github.com/sfg-taxonpages/cockroach/assets/61740366/19823231-6b28-487f-9ed5-f947a933ea06)

When I click on any thumbnail I expect a larger version of the photo to appear above.

**Comment by jlpereira** [comment]
This is a known issue: https://github.com/SpeciesFileGroup/taxonpages/issues/17

TIF images are not supported by browsers, this will be fixed when we move TaxonWorks to rails 7, creating new images with different sizes.

**Comment by hhopkins77** [comment]
Thanks @jlpereira.
