### ISSUE TITLE
Alienoptera and Umenocoleidae

### ISSUE THREAD

**Issue by dominicev** [sfg-taxonpages/cockroach#3]
Alienoptera is missing from Dictyoptera and Umenocoleidae should be sister to Alienoptera  or within it

**Comment by hhopkins77** [comment]
Strictly speaking we don't have a species file for Dictyoptera. This species file covers only what falls within Blattodea _sensu stricto_, but I have put them both in the workflow. These are not the only fossil creatures that exist in a sort of limbo (e.g. Permopsocida). Thanks for the input!
