### ISSUE TITLE
Most Ectobiidae genera are incertae sedis

### ISSUE THREAD

**Issue by dominicev** [sfg-taxonpages/cockroach#4]
I believe most of the genera listed under "Ectobiidae" are incertae sedis. This probably is because "Ectobiidae" previously encompassed all non-Blaberid Blaberoidea. On the original CSF page for Ectobiidae, these genera were probably listed there as unplaced in any subfamily, so now it appears that they are in Ectobiidae when in reality they are unplaced in Blaberoidea. Not all the genera obviously, but most of them.

**Comment by hhopkins77** [comment]
Happy to fix any of this Dominic. Just send the paper(s) where this is asserted, and/or a list of the genera that should be moved and we can cite you as the authority.
