### ISSUE TITLE
Dendroblatta  Rehn, 1916

### ISSUE THREAD

**Issue by dominicev** [sfg-taxonpages/cockroach#6]
https://cockroach.speciesfile.org/otus/861405/overview

Missing  D. falcifera Lopes, 2006 (paper: https://www.researchgate.net/publication/250034156_Duas_especies_novas_de_Dendroblatta_Rehn_Blattellidae_coletados_no_Acre_Brasil_em_ninhos_de_vespas?_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoic2VhcmNoIiwicG9zaXRpb24iOiJwYWdlSGVhZGVyIn19)

**Comment by cclucanas** [comment]
have included the two taxa.
