### ISSUE TITLE
Pycnoscelus gender agreement of species epithets

### ISSUE THREAD

**Issue by sjl197** [sfg-taxonpages/cockroach#9]
For
[Pycnoscelus Scudder, 1862](https://cockroach.speciesfile.org/otus/857029)
https://cockroach.speciesfile.org/otus/857029/overview

Please investigate gender presentation of at least these species "[aurantia Hanitsch, 1935](https://cockroach.speciesfile.org/otus/857030), [conferta (Walker, 1869)](https://cockroach.speciesfile.org/otus/857031) and [nigra (Brunner von Wattenwyl, 1865)](https://cockroach.speciesfile.org/otus/857036), [tenebrigera (Walker, 1868)](https://cockroach.speciesfile.org/otus/857054)
... versus adjectival masculine aurantius, confertus, niger, tenebrigerus. 

Cheers.
Stuart Longhorn

**Comment by hhopkins77** [comment]
Thank you Stuart! These are fixed.

This issue is created because our new platform has features that the old platform did not, and one of those has to do with the handling of name endings. You may find others as you navigate about the species file. Please report them here as you did in this case. I hope we will eventually find them all and get them fixed.

NB: the male of tenebrigera appears to be tenebriger.

Also, should you have any interest in learning TaxonWorks and helping with the database let me know at cockroachdoc@gmail.com. I can get you into one of our sandboxes and provide startup help/continuing ed.

Best,
Heidi Hopkins

**Comment by sjl197** [comment]
Dear Heidi,

Thanks for prompt response, glad this report via the Github system here works for you - in other Taxonworks projects these issues go unanswered. My request above originated via the backend of iNaturalist where a user had noticed a mismatch on one of the species epithets, so now thanks to your edits, then i'll get those (and a couple of other sites) inline. Taxonworks sometimes has quirky behaviour when it comes to the gender epithets - especially if the original author gets them 'wrong'.

Else, yes - my mistake - it seems better to use 'tenebriger' rather than 'tenebrigerus' (The latter as i understand it being a creative (neo)latinization which some authors seem to have historically done with modification of '-iger'/'-ifer' suffixes which had slipped my mind).

Thanks also for the direct contact point and the kind offer.

**Comment by hhopkins77** [comment]
Hi Stuart,

Please note: Issues regarding data filed on the following will be sent to my attention and you should hear from me within a week in most cases:

Cockroach SF
Dermaptera SF
Embioptera SF
Grylloblattodea SF
Isoptera SF
Mantophasmatodea SF
Permopsocida SF
Plecoptera SF
Psocodea SF
Zoraptera SF

If you do not have a response in short order when filing issues on these species files, please contact me directly by email.  We are more than a year post-migration to the new platform, and while most of the larger issues have been resolved, smaller ones still need clearing up. I appreciate all assistance bringing them to my attention!
H

**Comment by debpaul** [comment]
> in other Taxonworks projects these issues go unanswered.

Hi @sjl197 please let us know in which projects? You can send me an email if you prefer? dlpaul@illinois.edu I'll see what I can do.
